# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Dmitry Kostyaev
tagline:          ''
description:      'Machine Learning Research Engineer'
url:              https://dmkostyaev.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
profile_img:      /assets/small_avatar.png

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true

google_analytics: UA-47889318-2

disqus:
  shortname: kostyaev

rss: false
github: kostyaev
twitter: virtuozz0
twitter: virtuozz0
linkedin: https://www.linkedin.com/in/dmitry-kostyaev-20695573
